### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by vkats-spbu** [Ballyev/HomeAssignments#1]
<pre><font color="#26A269"><b>victor@victor-VirtualBox</b></font>:<font color="#12488B"><b>~/accesment/Ballyev/HelloWorld</b></font>$ make
g++ -std=c++17 -c main.cpp
<b>main.cpp:</b> In function ‘<b>int main()</b>’:
<b>main.cpp:7:22:</b> <font color="#C01C28"><b>error: </b></font>expected ‘<b>;</b>’ before ‘<b>string</b>’
    7 |    greetWord(&quot;World&quot;)
      |                      <font color="#C01C28"><b>^</b></font>
      |                      <font color="#26A269">;</font>
    8 |     <font color="#26A269">string</font> word;
      |     <font color="#26A269">~~~~~~</font>            
<b>main.cpp:11:22:</b> <font color="#C01C28"><b>error: </b></font>‘<b>word</b>’ was not declared in this scope
   11 |         getline(cin, <font color="#C01C28"><b>word</b></font>);
      |                      <font color="#C01C28"><b>^~~~</b></font>
make: *** [Makefile:9: main.o] Error 1
</pre>

Исправьте

**Comment by Ballyev** [comment]
Исправил

ср, 25 сент. 2024 г., 14:53 vkats-spbu ***@***.***>:

**Comment by vkats-spbu** [comment]
Хорошо. Добавьте обязательный комментарий в исходники и заголовок, и все будет зачтено

**Comment by Ballyev** [comment]
Добрый вечер!

Добавил.

Спасибо

чт, 26 сент. 2024 г., 22:18 vkats-spbu ***@***.***>:
